version: "3.6"

services:
  nginx:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - "./dist:/usr/share/nginx/html:ro"
      - "./conf/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./conf/mime.types:/etc/nginx/mime.types:ro"
      - "./conf/conf.d/:/etc/nginx/conf.d/:ro"
